declare var _XTFURLRequest: any
declare var _XTFURLResponse: any
declare var _XTFURLSession: any
declare var _XTFURLSessionTask: any
declare var _XTFData: any
declare var _XTFUserDefaults: any
declare var _XTFFileManager: any
declare var _XTFNotification: any
declare var _XTFNotificationCenter: any
declare var _XTFWebSocket: any
declare var _XTFDatabase: any