declare var objectRefs: any
declare var _XTRetain: any
declare var _XTRelease: any
declare var _XTFURLRequest: any
declare var _XTFURLResponse: any
declare var _XTFURLSession: any
declare var _XTFURLSessionTask: any
declare var _XTFData: any
declare var _XTFUserDefaults: any
declare var _XTFFileManager: any
declare var _XTFNotification: any
declare var _XTFNotificationCenter: any
declare var _XTFClassLoader: any
declare var _XTFWebSocket: any