declare var objectRefs: any
declare var _XTRetain: any
declare var _XTRelease: any
declare var _XTUIApplication: any
declare var _XTUIApplicationDelegate: any
declare var _XTUIView: any
declare var _XTUIWindow: any
declare var _XTUIViewController: any
declare var _XTUINavigationBar: any
declare var _XTUINavigationController: any
declare var _XTUIScreen: any
declare var _XTUIImage: any
declare var _XTUIImageView: any
declare var _XTUILabel: any
declare var _XTUIButton: any
declare var _XTUILayoutConstraint: any
declare var _XTUIFont: any
declare var _XTUIScrollView: any
declare var _XTUIListView: any
declare var _XTUIListCell: any
declare var _XTUITextField: any
declare var _XTUITextView: any
declare var _XTUITest: any
declare var _XTUICanvasView: any
declare var _XTUIDevice: any
declare var _XTUITextMeasurer: any
declare var _XTUIHRView: any
declare var _XTUIModal: any
declare var _XTUIWebView: any
declare var _XTUISwitch: any
declare var _XTUISlider: any
declare var _XTUIActivityIndicatorView: any
declare var _XTUIDebug: any
declare var _XTUIContext: any