declare const XTRApplication: any
declare const XTRApplicationDelegate: any
declare const XTRView: any
declare const XTRWindow: any
declare const XTRViewController: any
declare const XTRNavigationController: any
declare const XTRScreen: any
declare const XTRImage: any
declare const XTRImageView: any
declare const XTRLabel: any
declare const XTRButton: any
declare const XTRLayoutConstraint: any
declare const XTRFont: any
declare const XTRScrollView: any
declare const XTRListView: any
declare const XTRListCell: any
declare const XTRTextField: any
declare const XTRTextView: any
declare const XTRTest: any