declare var XTRApplication: any
declare var XTRApplicationDelegate: any
declare var XTRView: any
declare var XTRWindow: any
declare var XTRViewController: any
declare var XTRNavigationBar: any
declare var XTRNavigationController: any
declare var XTRScreen: any
declare var XTRImage: any
declare var XTRImageView: any
declare var XTRLabel: any
declare var XTRButton: any
declare var XTRLayoutConstraint: any
declare var XTRFont: any
declare var XTRScrollView: any
declare var XTRListView: any
declare var XTRListCell: any
declare var XTRTextField: any
declare var XTRTextView: any
declare var XTRTest: any
declare var XTRCanvasView: any
declare var XTRCustomView: any
declare var XTRDevice: any
declare var XTRTextMeasurer: any
declare var XTRHRView: any
declare var XTRModal: any
declare var XTRWebView: any
declare var XTRSwitch: any
declare var XTRSlider: any